services:
  app:
    image: golang:1.18-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "apk add --no-cache gcc musl-dev sqlite sqlite-dev && go run main.go"
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: alpine:3.16
    command: sh -c "apk update && apk add --no-cache sqlite sqlite-dev && tail -f /dev/null"
